[server]
name = ""
last_update = ""
path = ""

[test_place]
name = "test_place"
last_update = "10/3/23"
path = "C:\Users\nickt\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds"
